declare module 'lucide-react' {
  import { FC, SVGProps, ForwardRefExoticComponent, RefAttributes } from 'react';

  export interface IconProps extends SVGProps<SVGSVGElement> {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
    absoluteStrokeWidth?: boolean;
  }

  export type LucideIcon = ForwardRefExoticComponent<IconProps & RefAttributes<SVGSVGElement>>;

  export const Loader2: LucideIcon;
  export const UserCheck: LucideIcon;
  export const School: LucideIcon;
  export const LogOut: LucideIcon;
  export const Lock: LucideIcon;
  export const AlertTriangle: LucideIcon;
  export const CreditCard: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Database: LucideIcon;
  export const Check: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const Mail: LucideIcon;
  export const Phone: LucideIcon;
  export const User: LucideIcon;
  export const Plus: LucideIcon;
  export const Trash2: LucideIcon;
  export const Edit: LucideIcon;
  export const Save: LucideIcon;
  export const X: LucideIcon;
  export const Search: LucideIcon;
  export const Settings: LucideIcon;
  export const Bell: LucideIcon;
  export const Info: LucideIcon;
  export const CheckCircle2: LucideIcon;
  export const Upload: LucideIcon;
  export const Download: LucideIcon;
  export const RefreshCw: LucideIcon;
  export const Home: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Calendar: LucideIcon;
  export const GraduationCap: LucideIcon;
  export const Building2: LucideIcon;
  export const Users: LucideIcon;
  export const LayoutDashboard: LucideIcon;
  export const FileText: LucideIcon;
  export const PieChart: LucideIcon;
  export const HelpCircle: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const MoreHorizontal: LucideIcon;
  export const Book: LucideIcon;
  export const Clock: LucideIcon;
  export const Filter: LucideIcon;
  export const Grid: LucideIcon;
  export const List: LucideIcon;
  export const Share2: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const Copy: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const AlertCircle: LucideIcon;
  export const Activity: LucideIcon;
  export const ArrowUpRight: LucideIcon;
  export const ArrowDownRight: LucideIcon;
  export const ArrowUpLeft: LucideIcon;
  export const ArrowDownLeft: LucideIcon;
  export const CheckSquare: LucideIcon;
  export const CalendarDays: LucideIcon;
  export const Globe: LucideIcon;
  export const Clock3: LucideIcon;
  export const Menu: LucideIcon;
  export const Shield: LucideIcon;
  export const ShieldCheck: LucideIcon;
  export const Landmark: LucideIcon;
  export const Receipt: LucideIcon;
  export const Wallet: LucideIcon;
  export const BarChart3: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const MapPin: LucideIcon;
  export const Star: LucideIcon;
  export const Heart: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const Inbox: LucideIcon;
  export const Send: LucideIcon;
  export const UserPlus: LucideIcon;
  export const UserMinus: LucideIcon;
  export const Users2: LucideIcon;
  export const Pencil: LucideIcon;
  export const Trash: LucideIcon;
  export const EyeIcon: LucideIcon;
  export const Ban: LucideIcon;
  export const BookOpen: LucideIcon;
  export const PauseCircle: LucideIcon;
  export const PlayCircle: LucideIcon;
  export const CircleCheck: LucideIcon;
  export const CircleAlert: LucideIcon;
  export const CircleInfo: LucideIcon;
  export const CircleX: LucideIcon;
}
